/**
 * verify-world-id.ts — Verify a World ID proof via the World ID Cloud API
 *
 * This module is called by submit-claim.ts BEFORE submitting any claim onchain.
 * It reads a proof JSON file (generated by the World ID Developer Portal Simulator)
 * and POSTs it to the real World ID Cloud Verification API.
 *
 * If the API returns { "success": true }, the claim submission proceeds.
 * If the API returns an error, the script exits early — no transaction is sent.
 *
 * ── How to get your proof JSON ──────────────────────────────────────────────
 * 1. Go to https://developer.worldcoin.org/ and create an app (Staging env).
 * 2. In the app settings, create an Action called "submit-claim".
 * 3. Open the "Simulator" tab, then click "Use Simulator".
 * 4. Integrate IDKit in your frontend or use the Worldcoin Simulator directly:
 *    https://simulator.worldcoin.org/
 * 5. Paste the QR code data from IDKit into the Simulator.
 * 6. The Simulator will return a proof JSON object. Copy it and paste it into:
 *    claimshield/world-id-proof.json  (this file is gitignored)
 *
 * ── Environment Variables Required ──────────────────────────────────────────
 * WORLD_ID_APP_ID   — Your app_id from the Developer Portal (app_...)
 * WORLD_ID_ACTION   — The action string you created (e.g. "submit-claim")
 *
 * See: https://docs.world.org/world-id/reference/api
 */

import fs from 'fs'
import path from 'path'

export interface WorldIDProof {
    merkle_root: string
    nullifier_hash: string
    proof: string
    verification_level: 'orb' | 'device'
}

interface WorldIDVerifyResponse {
    success: boolean
    nullifier_hash?: string
    created_at?: string
    action?: string
    signal?: string
    code?: string
    detail?: string
    attribute?: string
}

/**
 * Reads the World ID proof from world-id-proof.json in the project root.
 * Throws if the file does not exist or is malformed.
 */
export function readProofFromFile(proofFilePath?: string): WorldIDProof {
    const filePath = proofFilePath ?? path.resolve(process.cwd(), 'world-id-proof.json')

    if (!fs.existsSync(filePath)) {
        throw new Error(
            `\n  ❌ World ID proof file not found: ${filePath}\n\n` +
            `  To generate a real proof:\n` +
            `  1. Go to https://developer.worldcoin.org/ → your app → Simulator tab\n` +
            `  2. Open https://simulator.worldcoin.org/ and scan the QR code\n` +
            `  3. Click "Approve" in the Simulator\n` +
            `  4. Copy the proof JSON and save it to: claimshield/world-id-proof.json\n`
        )
    }

    const raw = fs.readFileSync(filePath, 'utf-8')
    try {
        return JSON.parse(raw) as WorldIDProof
    } catch {
        throw new Error(`world-id-proof.json is not valid JSON. Please check the file contents.`)
    }
}

/**
 * Calls the real World ID Cloud Verification API.
 * Returns the nullifier_hash on success (uniquely identifies this human for this action).
 * Throws on verification failure.
 */
export async function verifyWorldIDProof(proof: WorldIDProof): Promise<string> {
    const appId = process.env.WORLD_ID_APP_ID
    const action = process.env.WORLD_ID_ACTION ?? 'submit-claim'

    if (!appId) {
        throw new Error(
            `WORLD_ID_APP_ID is not set in your .env file.\n` +
            `Create an app at https://developer.worldcoin.org/ and paste the app_id.`
        )
    }

    const url = `https://developer.worldcoin.org/api/v1/verify/${appId}`

    const body = {
        nullifier_hash: proof.nullifier_hash,
        merkle_root: proof.merkle_root,
        proof: proof.proof,
        verification_level: proof.verification_level,
        action: action,
        signal: '',
    }

    console.log(`\n  [World ID] Sending proof to World ID Cloud API...`)
    console.log(`  [World ID] URL    : ${url}`)
    console.log(`  [World ID] Action : ${action}`)
    console.log(`  [World ID] Level  : ${proof.verification_level}`)

    const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
    })

    const json: WorldIDVerifyResponse = await res.json() as WorldIDVerifyResponse

    if (!res.ok || !json.success) {
        const reason = json.detail ?? json.code ?? 'Unknown error'
        throw new Error(
            `\n  ❌ World ID verification FAILED\n` +
            `  Reason  : ${reason}\n` +
            `  Code    : ${json.code ?? 'N/A'}\n\n` +
            `  Is your proof fresh? Proofs expire — generate a new one from the Simulator.\n`
        )
    }

    return json.nullifier_hash ?? proof.nullifier_hash
}

/**
 * Full verification flow: read proof file → call World ID API → return nullifier.
 * This is the function called by submit-claim.ts.
 */
export async function runWorldIDVerification(proofFilePath?: string): Promise<string> {
    const proof = readProofFromFile(proofFilePath)
    const nullifierHash = await verifyWorldIDProof(proof)
    return nullifierHash
}
